### ISSUE TITLE
No password was Found

### ISSUE THREAD

**Issue by Calmest205PL** [m-primo/Facebook-Brute-Force#5]
I was trying to brute force my account on fb and I've created a dictionary which contained my password but the program returned 'No password was found'

**Comment by m-primo** [comment]
Hey.
So sorry for the late reply, I was investigating it.

Facebook is trying to limit the brute-forcing and I think the script is like 70% working or something.
Anyway, in the next few weeks, I'll make a new open-source script, and it will 100% work.
